/**
 * 小元适配器快速开始示例
 *
 * 这个示例展示了如何快速开始使用小元适配器
 */

import { XiaoyuanAdapter } from './index';
import type { ServiceType, MessageType } from './types';

// 配置
const config = {
  apiKey: 'your-api-key', // 替换为实际的 API Key
  coreApiUrl: 'http://localhost:5000/api',
  wsEndpoint: 'ws://localhost:5000/ws',

  // 启用所有服务
  services: {
    apiManagement: {
      enabled: true,
      autoDocument: true,
      testingEnabled: true,
    },
    pluginDevelopment: {
      enabled: true,
      templatesPath: './templates',
      autoGenerateDocs: true,
    },
    sdkManagement: {
      enabled: true,
      checkUpdatesInterval: 86400000,
      autoNotify: true,
    },
    codeReview: {
      enabled: true,
      strictMode: false,
    },
  },
};

async function quickStart() {
  console.log('🚀 小元适配器快速开始示例\n');

  // 1. 创建适配器实例
  console.log('1️⃣ 创建适配器实例...');
  const adapter = new XiaoyuanAdapter(config);

  // 设置事件监听器
  adapter.on('connected', () => {
    console.log('✅ 已连接到玄玑核心服务\n');
  });

  adapter.on('disconnected', () => {
    console.log('⚠️  与玄玑核心服务断开连接\n');
  });

  adapter.on('error', (error) => {
    console.error('❌ 错误:', error.message);
  });

  // 2. 连接到核心服务
  console.log('2️⃣ 连接到核心服务...');
  await adapter.connect();

  // 3. 创建会话
  console.log('3️⃣ 创建会话...');
  const session = await adapter.createSession('developer-example');
  console.log('✅ 会话创建成功:', session.id, '\n');

  // 4. 示例：API 管理服务
  console.log('4️⃣ API 管理服务示例\n');

  const apiService = adapter.getApiManagementService();
  if (apiService) {
    console.log('📋 获取 API 端点列表...');
    const endpoints = await apiService.getAllEndpoints();
    console.log(`✅ 找到 ${endpoints.length} 个 API 端点\n`);

    if (endpoints.length === 0) {
      // 添加示例端点
      console.log('📝 添加示例 API 端点...');
      await apiService.addEndpoint({
        id: 'users-api',
        path: '/api/v1/users',
        method: 'GET',
        description: '获取用户列表',
        tags: ['users', 'read'],
        parameters: [
          {
            name: 'page',
            type: 'number',
            required: false,
            description: '页码',
          },
          {
            name: 'limit',
            type: 'number',
            required: false,
            description: '每页数量',
          },
        ],
        responses: {
          200: {
            type: 'array',
            description: '用户列表',
          },
        },
        authRequired: true,
      });
      console.log('✅ 示例端点添加成功\n');
    }
  }

  // 5. 示例：发送消息
  console.log('5️⃣ 发送消息示例\n');

  const response1 = await adapter.handleMessage(session.id, {
    type: MessageType.TEXT,
    role: 'user',
    content: '帮我生成一个 API 文档',
    serviceType: ServiceType.API_MANAGEMENT as ServiceType,
    timestamp: Date.now(),
  });

  console.log('📨 响应:', response1.content, '\n');

  // 6. 示例：代码审查
  console.log('6️⃣ 代码审查示例\n');

  const reviewService = adapter.getCodeReviewService();
  if (reviewService) {
    const code = `function example() {
  const result = [];
  for (let i = 0; i < data.length; i++) {
    for (let j = 0; j < data[i].items.length; j++) {
      result.push(data[i].items[j]);
    }
  }
  return result;
}`;

    console.log('🔍 审查代码...\n');
    const reviewResult = await reviewService.reviewCode({
      code,
      language: 'javascript',
    });

    console.log(`📊 代码评分: ${reviewResult.overallScore}/100`);
    console.log(`🔍 发现问题: ${reviewResult.issues.length} 个`);
    console.log(`💡 建议: ${reviewSuggestions.length} 个\n`);

    reviewResult.issues.forEach(issue => {
      console.log(`   [${issue.severity.toUpperCase()}] ${issue.title}`);
      console.log(`   位置: 第 ${issue.line} 行\n`);
    });
  }

  // 7. 示例：插件开发
  console.log('7️⃣ 插件开发示例\n');

  const pluginService = adapter.getPluginDevelopmentService();
  if (pluginService) {
    console.log('📋 获取插件模板列表...');
    const templates = await pluginService.getAllTemplates();
    console.log(`✅ 找到 ${templates.length} 个插件模板\n`);

    templates.slice(0, 3).forEach(t => {
      console.log(`   - ${t.name}: ${t.description}`);
    });
    console.log('');
  }

  // 8. 示例：SDK 管理
  console.log('8️⃣ SDK 管理示例\n');

  const sdkService = adapter.getSdkManagementService();
  if (sdkService) {
    console.log('📋 获取 SDK 列表...');
    const sdks = await sdkService.getAllSdks();
    console.log(`` 找到 ${sdks.length} 个 SDK\n`);

    sdks.forEach(sdk => {
      console.log(`   - ${sdk.name}:`);
      console.log(`     当前版本: ${sdk.currentVersion}`);
      console.log(`     最新版本: ${sdk.latestVersion}`);
      console.log(`     平台: ${sdk.platforms.join(', ')}\n`);
    });
  }

  // 9. 示例：生成 API 文档
  console.log('9️⃣ 生成 API 文档示例\n');

  if (apiService) {
    console.log('📝 生成 Markdown 格式文档...');
    const doc = await apiService.generateDocumentation('markdown');
    console.log('✅ 文档生成成功（前 200 字符）：\n');
    console.log(doc.substring(0, 200) + '...\n');
  }

  // 10. 示例：代码审查 - 安全漏洞扫描
  console.log('🔟 安全漏洞扫描示例\n');

  if (reviewService) {
    const vulnerableCode = `const password = 'hardcoded_password';
    const query = "SELECT * FROM users WHERE id = " + userId;
    document.body.innerHTML = userInput;`;

    console.log('🔍 扫描安全漏洞...');
    const vulnerabilities = await reviewService.scanSecurityVulnerabilities(
      vulnerableCode,
      'javascript',
      'example.js'
    );

    console.log(`✅ 发现 ${vulnerabilities.length} 个安全漏洞\n`);

    vulnerabilities.forEach(vuln => {
      console.log(`   [${vuln.severity.toUpperCase()}] ${vuln.title}`);
      console.log(`   描述: ${vuln.description}`);
      console.log(`   修复建议: ${vuln.recommendation}\n`);
    });
  }

  // 11. 健康检查
  console.log('1️⃣1️⃣ 健康检查\n');

  const isHealthy = await adapter.healthCheck();
  console.log(`${isHealthy ? '✅' : '❌'} 服务健康状态: ${isHealthy ? '健康' : '不健康'}\n`);

  // 12. 断开连接
  console.log('1️⃣2️⃣ 断开连接...\n');
  await adapter.disconnect();
  console.log('✅ 已断开连接\n');

  console.log('🎉 快速开始示例完成！');
}

// 主函数
async function main() {
  try {
    await quickStart();
  } catch (error: any) {
    console.error('❌ 发生错误:', error.message);
    console.error('堆栈:', error.stack);
    process.exit(1);
  }
}

// 如果直接运行此文件，执行快速开始示例
if (require.main === module) {
  main();
}

/**
 * 其他实用示例函数
 */

/**
 * 代码审查助手
 */
async function codeReviewAssistant(adapter: XiaoyuanAdapter, session: any, code: string, language: string) {
  const reviewService = adapter.getCodeReviewService();
  if (!reviewService) {
    throw new Error('代码审查服务未启用');
  }

  const result = await reviewService.reviewCode({ code, language });

  console.log('📊 代码审查结果\n');
  console.log(`总体评分: ${result.overallScore}/100`);
  console.log(`复杂度: ${result.metrics.complexity}`);
  console.log(`可维护性: ${result.metrics.maintainabilityIndex}\n`);

  if (result.issues.length > 0) {
    console.log('发现问题：');
    result.issues.forEach(issue => {
      console.log(`  - [${issue.severity}] ${issue.title}`);
      if (issue.line) {
        console.log(`    位置: 第 ${issue.line} 行`);
      }
    });
  }

  if (result.suggestions.length > 0) {
    console.log('\n优化建议：');
    result.suggestions.forEach(suggestion => {
      console.log(`  - [${suggestion.type}] ${suggestion.title}`);
    });
  }
}

/**
 * 插件开发助手
 */
async function pluginDevAssistant(adapter: XiaoyuanAdapter, session: any, pluginName: string, templateId: string) {
  const pluginService = adapter.getPluginDevelopmentService();
  if (!pluginService) {
    throw new Error('插件开发服务未启用');
  }

  // 创建插件项目
  const files = await pluginService.createPlugin(templateId, pluginName);
  console.log(`✅ 创建插件项目: ${pluginName}`);
  console.log(`   文件数: ${files.length}\n`);

  files.forEach(file => {
    console.log(`   - ${file.path}`);
    if (file.description) {
      console.log(`     ${file.description}`);
    }
  });

  // 生成 README
  const readme = await pluginService.generateReadme(templateId, pluginName);
  console.log('\n✅ README 文档生成成功');
}

/**
 * API 管理助手
 */
async function apiManagementAssistant(adapter: XiaoyuanAdapter, session: any) {
  const apiService = adapter.getApiManagementService();
  if (!apiService) {
    throw new Error('API 管理服务未启用');
  }

  // 获取所有端点
  const endpoints = await apiService.getAllEndpoints();
  console.log(`📋 API 端点总数: ${endpoints.length}\n`);

  // 按方法分组
  const byMethod = endpoints.reduce((acc, ep) => {
    if (!acc[ep.method]) {
      acc[ep.method] = 0;
    }
    acc[ep.method]++;
    return acc;
  }, {} as Record<string, number>);

  console.log('按方法分类：');
  Object.entries(byMethod).forEach(([method, count]) => {
    console.log(`  ${method}: ${count} 个`);
  });

  // 生成文档
  const doc = await apiService.generateDocumentation('openapi');
  console.log('\n✅ OpenAPI 文档生成成功');
}

// 导出辅助函数
export {
  quickStart,
  codeReviewAssistant,
  pluginDevAssistant,
  apiManagementAssistant,
};
