/**
 * 小元 - 开发者端智能助手适配层
 * 配置文件
 */

import { XiaoyuanConfig } from '../types';

/**
 * 默认配置
 */
export const DEFAULT_CONFIG: XiaoyuanConfig = {
  // 核心连接
  coreApiUrl: process.envAPI_URL || 'http://localhost:5000/api',
  wsEndpoint: process.env.WS_ENDPOINT || 'ws://localhost:5000/ws',
  apiKey: process.env.API_KEY,

  // 服务配置
  services: {
    apiManagement: {
      enabled: true,
      autoDocument: true,
      testingEnabled: true,
    },
    pluginDevelopment: {
      enabled: true,
      templatesPath: './templates',
      autoGenerateDocs: true,
    },
    sdkManagement: {
      enabled: true,
      checkUpdatesInterval: 86400000,  // 24 hours
      autoNotify: true,
    },
    codeReview: {
      enabled: true,
      strictMode: false,
    },
  },

  // 对话配置
  dialog: {
    maxHistoryLength: 100,
    timeout: 30000,
    enableStream: true,
  },

  // 开发者配置
  developer: {
    preferredLanguage: 'typescript',
    codeStyle: 'eslint',
  },

  // 日志配置
  logging: {
    level: process.env.LOG_LEVEL as any || 'info',
    enableConsole: true,
  },
};

/**
 * 代码审查规则配置
 */
export const DEFAULT_REVIEW_RULES = {
  // 安全规则
  security: [
    {
      id: 'no-hardcoded-secrets',
      name: '不允许硬编码密钥',
      category: 'security' as const,
      severity: 'critical' as const,
      enabled: true,
    },
    {
      id: 'sql-injection',
      name: 'SQL 注入风险',
      category: 'security' as const,
      severity: 'high' as const,
      enabled: true,
    },
    {
      id: 'xss-vulnerability',
      name: 'XSS 跨站脚本风险',
      category: 'security' as const,
      severity: 'high' as const,
      enabled: true,
    },
  ],

  // 性能规则
  performance: [
    {
      id: 'no-nested-loops',
      name: '避免深层嵌套循环',
      category: 'performance' as const,
      severity: 'medium' as const,
      enabled: true,
    },
    {
      id: 'efficient-data-structures',
      name: '使用高效数据结构',
      category: 'performance' as const,
      severity: 'medium' as const,
      enabled: true,
    },
    {
      id: 'no-memory-leaks',
      name: '避免内存泄漏',
      category: 'performance' as const,
      severity: 'high' as const,
      enabled: true,
    },
  ],

  // 代码质量规则
  quality: [
    {
      id: 'no-console-log',
      name: '生产代码不应包含 console.log',
      category: 'quality' as const,
      severity: 'low' as const,
      enabled: true,
    },
    {
      id: 'consistent-naming',
      name: '命名一致性',
      category: 'quality' as const,
      severity: 'medium' as const,
      enabled: true,
    },
    {
      id: 'proper-error-handling',
      name: '适当的错误处理',
      category: 'quality' as const,
      severity: 'high' as const,
      enabled: true,
    },
  ],

  // 代码风格规则
  style: [
    {
      id: 'max-line-length',
      name: '代码行长度限制',
      category: 'style' as const,
      severity: 'low' as const,
      enabled: true,
      config: { maxLength: 120 },
    },
    {
      id: 'indentation',
      name: '代码缩进',
      category: 'style' as const,
      severity: 'low' as const,
      enabled: true,
      config: { spaces: 2 },
    },
  ],
};

/**
 * 插件模板路径
 */
export const PLUGIN_TEMPLATES = {
  typescript: [
    'basic-plugin',
    'api-plugin',
    'ui-plugin',
    'middleware-plugin',
  ],
  javascript: [
    'basic-plugin',
    'api-plugin',
  ],
  python: [
    'basic-plugin',
    'service-plugin',
  ],
};

/**
 * SDK 信息配置
 */
export const SUPPORTED_SDKS = {
  javascript: {
    name: 'JavaScript SDK',
    latestVersion: '1.2.0',
    platforms: ['Node.js', 'Browser'],
  },
  python: {
    name: 'Python SDK',
    latestVersion: '1.1.0',
    platforms: ['Python 3.8+'],
  },
  typescript: {
    name: 'TypeScript SDK',
    latestVersion: '1.2.0',
    platforms: ['Node.js', 'Browser'],
  },
};

/**
 * API 文档模板
 */
export const API_DOC_TEMPLATE = `# API 文档

## 概述
本 API 提供 {service_name} 的核心功能。

## 认证
所有 API 请求需要在 Header 中包含有效的 API Key:
\`\`\`
Authorization: Bearer {api_key}
\`\`\`

## 端点列表
{endpoints}

## 错误码
| 错误码 | 描述 |
|--------|------|
| 400 | 请求参数错误 |
| 401 | 认证失败 |
| 403 | 权限不足 |
| 404 | 资源不存在 |
| 500 | 服务器内部错误 |
`;

/**
 * 代码审查报告模板
 */
export const CODE_REPORT_TEMPLATE = `# 代码审查报告

## 概览
- 总体评分: {score}/100
- 代码行数: {lines}
- 复杂度: {complexity}
- 可维护性: {maintainability}

## 问题汇总
{issues}

## 建议
{suggestions}

## 指标详情
{metrics}
`;

/**
 * 环境变量验证
 */
export function validateConfig(config: Partial<XiaoyuanConfig>): void {
  if (!config.coreApiUrl) {
    throw new Error('coreApiUrl is required');
  }

  if (!config.wsEndpoint) {
    throw new Error('wsEndpoint is required');
  }

  if (config.services?.apiManagement?.enabled && !config.coreApiUrl) {
    throw new Error('API management requires coreApiUrl');
  }

  if (config.services?.sdkManagement?.enabled && config.services?.sdkManagement?.checkUpdatesInterval && config.services.sdkManagement.checkUpdatesInterval < 60000) {
    throw new Error('SDK update check interval must be at least 1 minute');
  }
}

/**
 * 创建配置
 */
export function createConfig(overrides?: Partial<XiaoyuanConfig>): XiaoyuanConfig {
  const config = {
    ...DEFAULT_CONFIG,
    ...overrides,
    services: {
      ...DEFAULT_CONFIG.services,
      ...overrides?.services,
    },
    dialog: {
      ...DEFAULT_CONFIG.dialog,
      ...overrides?.dialog,
    },
    developer: {
      ...DEFAULT_CONFIG.developer,
      ...overrides?.developer,
    },
    logging: {
      ...DEFAULT_CONFIG.logging,
      ...overrides?.logging,
    },
  };

  validateConfig(config);
  return config;
}
